version: '3.4'
networks:
    consul_cluster:

volumes:
    auth-db-postgres:
    

services:
  portalapigateway:
    image: ${DOCKER_REGISTRY-}portalapigateway
    networks:
        consul_cluster:
            aliases:
                - apigate1.internal
    ports:
        - "7000:7000"
    build:
      context: .
      dockerfile: PortalApiGateway/Dockerfile

  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    networks:
        consul_cluster:
            aliases:
                - productservice.internal
    ports:
        - "7010:7010"
        - "7011:7011"
    build:
      context: .
      dockerfile: ProductService/Dockerfile

  dev-consul:
    container_name: "dev-consul"
    build:
        context: ConsulSetup/
        dockerfile: Dockerfile
    networks:
        consul_cluster:
            aliases:
                - consul.internal
    ports:
        - "8500:8500"
        - "8600:8600"
    restart: always
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client='0.0.0.0'"

  authservice:
    container_name: AuthService
    image: ${DOCKER_REGISTRY-}authservice
    networks:
        consul_cluster:
            aliases:
                - authservice.internal
    build:
      context: AuthService/AuthServiceApp/
      dockerfile: Dockerfile

  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    volumes:
        - auth-db-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auther
      POSTGRES_PASSWORD: P@ssw0rd
    restart: always
    ports:
        - 5432:5432
    networks: 
        consul_cluster:
            aliases:
                - postgresdb.internal